# Generated by Django 5.2 on 2026-09-08 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source', models.TextField()),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CropReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=10)),
                ('key', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('individual', models.CharField(blank=True, max_length=100)),
                ('label', models.JSONField()),
                ('prediction', models.JSONField()),
                ('ai_review', models.JSONField(blank=True, default=dict)),
                ('decision', models.CharField(choices=[('pending', '미판정'), ('accept', '사용 가능'), ('repair', '수정 필요'), ('exclude', '사용 제외'), ('hold', '보류')], default='pending', max_length=20)),
                ('image_quality', models.CharField(choices=[('unknown', '미확인'), ('good', '적절함'), ('bad', '문제 있음'), ('missing', '없음'), ('uncertain', '불확실')], default='unknown', max_length=20)),
                ('mask_quality', models.CharField(choices=[('unknown', '미확인'), ('good', '적절함'), ('bad', '문제 있음'), ('missing', '없음'), ('uncertain', '불확실')], default='unknown', max_length=20)),
                ('base_quality', models.CharField(choices=[('unknown', '미확인'), ('good', '적절함'), ('bad', '문제 있음'), ('missing', '없음'), ('uncertain', '불확실')], default='unknown', max_length=20)),
                ('reviewer', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='viewer.run')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ReviewHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('judgment', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='viewer.cropreview')),
            ],
            options={
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('crop', 'version'), name='unique_review_version')],
            },
        ),
        migrations.AddConstraint(
            model_name='cropreview',
            constraint=models.UniqueConstraint(fields=('run', 'kind', 'key'), name='unique_run_crop'),
        ),
    ]
